[package]
name = "weebweeb/particlegun"
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
authors = ["Alice Oppenheim <epicalice1234@gmail.com>"]
license = "MIT"
description = "Modular weapons framework for Roblox"
include = ["src"]

[dependencies]
